# Generated by Django 4.0.1 on 2023-02-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_alter_district_lat_alter_district_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazila',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.district'),
        ),
    ]
