# Generated by Django 4.0.1 on 2023-02-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_alter_upazila_district_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_doner',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.district'),
        ),
        migrations.AlterField(
            model_name='blood_doner',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.division'),
        ),
        migrations.AlterField(
            model_name='blood_doner',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.upazila'),
        ),
    ]
