# Generated by Django 4.0.1 on 2023-02-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_alter_blood_doner_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blood_bank',
            options={'verbose_name': 'Blood Bank', 'verbose_name_plural': 'Blood Banks'},
        ),
        migrations.AlterModelOptions(
            name='blood_doner',
            options={'ordering': ['user', 'first_name', 'last_name', 'blood_group', 'contact_no', 'address_line_1', 'division', 'district', 'upazila', 'country', 'data_of_birth', 'gender', 'last_donation_date', 'is_active'], 'verbose_name': 'Blood Doner', 'verbose_name_plural': 'Blood Doners'},
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.district'),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.division'),
        ),
        migrations.AlterField(
            model_name='blood_bank',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.upazila'),
        ),
    ]
