# Generated by Django 4.0.1 on 2023-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_alter_blood_bank_options_alter_blood_doner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blood_bank',
            options={'ordering': ['user', 'name', 'contact_no', 'address_line_1', 'division', 'district', 'upazila', 'zip_code', 'country', 'is_active'], 'verbose_name': 'Blood Bank', 'verbose_name_plural': 'Blood Banks'},
        ),
        migrations.AddField(
            model_name='blood_bank',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
