# Generated by Django 4.0.1 on 2023-02-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0006_alter_blood_bank_options_blood_bank_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blood_bank',
            options={'verbose_name': 'Blood Bank', 'verbose_name_plural': 'Blood Banks'},
        ),
        migrations.AlterModelOptions(
            name='blood_doner',
            options={'verbose_name': 'Blood Doner', 'verbose_name_plural': 'Blood Doners'},
        ),
    ]
